### PR TITLE
Update packaging_tools.md

### PR DESCRIPTION
**Pull request by DahanDv**
I hope you find this helpful :) 

As of my current understanding and experience, Hatch allows *some* Python version management.

For reference, here's Hatch's relevant docs section: https://hatch.pypa.io/latest/cli/reference/#hatch-python

### CODE REVIEW

**Comment by zotroneneis** [comment]
Thanks! I can't find the detail that it only allows for major versions. Where did you read that?

**Comment by DahanDv** [comment]
> Thanks! *I can't find the detail that it only allows for major versions.* Where did you read that?

Ho no! 
I just realized I made an error there. **(Fixed it.)**
I meant it will allow you to choose between major.minor versions (e.g., 3.7, 3.10, etc.) - but not patches! 


Regarding my conclusion that it won't allow for patch versions:
I couldn't find a clear-cut explanation for it on the Hatch's docs, and after some testing, I concluded the above. 

_Side note: I am working in parallel on patching the Hatch docs regarding this specific section, but the maintainer started enforcing a higher standard on the matter (in a good way) - so it takes a little more time. (if you're interested, [read all the discussions he's pointing to](https://github.com/pypa/hatch/pull/1208) - TL;DR: he wants to go all in on [diataxis documentation framework](https://diataxis.fr/) )
We can hold this one open until I come back when my patch is merged into Hatch's docs (and thus 100% verified the correctness by the maintainer) - that would be understandable, and I'll happily cooperate._ 

How I verified it:

1. Fresh Linux VM
2. installed Hatch
3. initiate demo project
4. > `hatch python show` yields the list of available Python versions:
image

5. if you try to install a patch version, you'll get the message: `Unknown distributions:`
image

6. doing the same without specifying the patch version:
image

Let me know your thoughts :)

**Review by ofek — APPROVED** [review]
lgtm

**Comment by zotroneneis** [comment]
Thanks a lot, I will update the article!

**Comment by DahanDv** [comment]
@zotroneneis 
I'm sorry this one didn't live up to your standards. Judging by the beautiful article you put together, I agree with the protective mindset :100: 
Promise to be better next time! Good vibes :)

**Comment by zotroneneis** [comment]
@DahanDv Not at all! Thanks for helping, I just like using my own words for the articles :)

**Pull request closed without merging**
